sudo: false
env:
  matrix:
    - SUITE=server RUBY_VERSION=2.3.1
before_install: source ci/before_install
before_script: ci/before_script
install: ci/install
script: ci/script
after_script: ci/after_script
